// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: client.proto

package fredclient

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRole int32

const (
	UserRole_ReadKeygroup       UserRole = 0
	UserRole_WriteKeygroup      UserRole = 1
	UserRole_ConfigureReplica   UserRole = 2
	UserRole_ConfigureTrigger   UserRole = 3
	UserRole_ConfigureKeygroups UserRole = 4
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "ReadKeygroup",
		1: "WriteKeygroup",
		2: "ConfigureReplica",
		3: "ConfigureTrigger",
		4: "ConfigureKeygroups",
	}
	UserRole_value = map[string]int32{
		"ReadKeygroup":       0,
		"WriteKeygroup":      1,
		"ConfigureReplica":   2,
		"ConfigureTrigger":   3,
		"ConfigureKeygroups": 4,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_client_proto_enumTypes[0].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_client_proto_enumTypes[0]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{0}
}

type Version struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       map[string]uint64      `protobuf:"bytes,1,rep,name=version,proto3" json:"version,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{1}
}

func (x *Version) GetVersion() map[string]uint64 {
	if x != nil {
		return x.Version
	}
	return nil
}

type CreateKeygroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keygroup      string                 `protobuf:"bytes,1,opt,name=keygroup,proto3" json:"keygroup,omitempty"`
	Mutable       bool                   `protobuf:"varint,2,opt,name=mutable,proto3" json:"mutable,omitempty"`
	Expiry        int64                  `protobuf:"varint,3,opt,name=expiry,proto3" json:"expiry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateKeygroupRequest) Reset() {
	*x = CreateKeygroupRequest{}
	mi := &file_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateKeygroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateKeygroupRequest) ProtoMessage() {}

func (x *CreateKeygroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateKeygroupRequest.ProtoReflect.Descriptor instead.
func (*CreateKeygroupRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{2}
}

func (x *CreateKeygroupRequest) GetKeygroup() string {
	if x != nil {
		return x.Keygroup
	}
	return ""
}

func (x *CreateKeygroupRequest) GetMutable() bool {
	if x != nil {
		return x.Mutable
	}
	return false
}

func (x *CreateKeygroupRequest) GetExpiry() int64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

type DeleteKeygroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keygroup      string                 `protobuf:"bytes,1,opt,name=keygroup,proto3" json:"keygroup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKeygroupRequest) Reset() {
	*x = DeleteKeygroupRequest{}
	mi := &file_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKeygroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKeygroupRequest) ProtoMessage() {}

func (x *DeleteKeygroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKeygroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteKeygroupRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteKeygroupRequest) GetKeygroup() string {
	if x != nil {
		return x.Keygroup
	}
	return ""
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keygroup      string                 `protobuf:"bytes,1,opt,name=keygroup,proto3" json:"keygroup,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Versions      []*Version             `protobuf:"bytes,3,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{4}
}

func (x *ReadRequest) GetKeygroup() string {
	if x != nil {
		return x.Keygroup
	}
	return ""
}

func (x *ReadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReadRequest) GetVersions() []*Version {
	if x != nil {
		return x.Versions
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Val           string                 `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	Version       *Version               `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{5}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetVal() string {
	if x != nil {
		return x.Val
	}
	return ""
}

func (x *Item) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Item                `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_client_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{6}
}

func (x *ReadResponse) GetData() []*Item {
	if x != nil {
		return x.Data
	}
	return nil
}

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keygroup      string                 `protobuf:"bytes,1,opt,name=keygroup,proto3" json:"keygroup,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Count         uint64                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_client_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{7}
}

func (x *ScanRequest) GetKeygroup() string {
	if x != nil {
		return x.Keygroup
	}
	return ""
}

func (x *ScanRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScanRequest) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Item                `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_client_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{8}
}

func (x *ScanResponse) GetData() []*Item {
	if x != nil {
		return x.Data
	}
	return nil
}

type KeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keygroup      string                 `protobuf:"bytes,1,opt,name=keygroup,proto3" json:"keygroup,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Count         uint64                 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeysRequest) Reset() {
	*x = KeysRequest{}
	mi := &file_client_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeysRequest) ProtoMessage() {}

func (x *KeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeysRequest.ProtoReflect.Descriptor instead.
func (*KeysRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{9}
}

func (x *KeysRequest) GetKeygroup() string {
	if x != nil {
		return x.Keygroup
	}
	return ""
}

func (x *KeysRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KeysRequest) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       *Version               `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_client_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{10}
}

func (x *Key) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Key) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

type KeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*Key                 `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeysResponse) Reset() {
	*x = KeysResponse{}
	mi := &file_client_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeysResponse) ProtoMessage() {}

func (x *KeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeysResponse.ProtoReflect.Descriptor instead.
func (*KeysResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{11}
}

func (x *KeysResponse) GetKeys() []*Key {
	if x != nil {
		return x.Keys
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keygroup      string                 `protobuf:"bytes,1,opt,name=keygroup,proto3" json:"keygroup,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Versions      []*Version             `protobuf:"bytes,4,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_client_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateRequest) GetKeygroup() string {
	if x != nil {
		return x.Keygroup
	}
	return ""
}

func (x *UpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *UpdateRequest) GetVersions() []*Version {
	if x != nil {
		return x.Versions
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *Version               `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_client_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateResponse) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

type AppendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keygroup      string                 `protobuf:"bytes,1,opt,name=keygroup,proto3" json:"keygroup,omitempty"`
	Id            uint64                 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendRequest) Reset() {
	*x = AppendRequest{}
	mi := &file_client_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRequest) ProtoMessage() {}

func (x *AppendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRequest.ProtoReflect.Descriptor instead.
func (*AppendRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{14}
}

func (x *AppendRequest) GetKeygroup() string {
	if x != nil {
		return x.Keygroup
	}
	return ""
}

func (x *AppendRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AppendRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type AppendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendResponse) Reset() {
	*x = AppendResponse{}
	mi := &file_client_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendResponse) ProtoMessage() {}

func (x *AppendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendResponse.ProtoReflect.Descriptor instead.
func (*AppendResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{15}
}

func (x *AppendResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keygroup      string                 `protobuf:"bytes,1,opt,name=keygroup,proto3" json:"keygroup,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Versions      []*Version             `protobuf:"bytes,3,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_client_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteRequest) GetKeygroup() string {
	if x != nil {
		return x.Keygroup
	}
	return ""
}

func (x *DeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteRequest) GetVersions() []*Version {
	if x != nil {
		return x.Versions
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *Version               `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_client_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteResponse) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

type AddReplicaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keygroup      string                 `protobuf:"bytes,1,opt,name=keygroup,proto3" json:"keygroup,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Expiry        int64                  `protobuf:"varint,3,opt,name=expiry,proto3" json:"expiry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddReplicaRequest) Reset() {
	*x = AddReplicaRequest{}
	mi := &file_client_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddReplicaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddReplicaRequest) ProtoMessage() {}

func (x *AddReplicaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddReplicaRequest.ProtoReflect.Descriptor instead.
func (*AddReplicaRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{18}
}

func (x *AddReplicaRequest) GetKeygroup() string {
	if x != nil {
		return x.Keygroup
	}
	return ""
}

func (x *AddReplicaRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AddReplicaRequest) GetExpiry() int64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

type GetKeygroupInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keygroup      string                 `protobuf:"bytes,1,opt,name=keygroup,proto3" json:"keygroup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeygroupInfoRequest) Reset() {
	*x = GetKeygroupInfoRequest{}
	mi := &file_client_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeygroupInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeygroupInfoRequest) ProtoMessage() {}

func (x *GetKeygroupInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeygroupInfoRequest.ProtoReflect.Descriptor instead.
func (*GetKeygroupInfoRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{19}
}

func (x *GetKeygroupInfoRequest) GetKeygroup() string {
	if x != nil {
		return x.Keygroup
	}
	return ""
}

type GetKeygroupInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mutable       bool                   `protobuf:"varint,1,opt,name=mutable,proto3" json:"mutable,omitempty"`
	Replica       []*KeygroupReplica     `protobuf:"bytes,2,rep,name=replica,proto3" json:"replica,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeygroupInfoResponse) Reset() {
	*x = GetKeygroupInfoResponse{}
	mi := &file_client_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeygroupInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeygroupInfoResponse) ProtoMessage() {}

func (x *GetKeygroupInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeygroupInfoResponse.ProtoReflect.Descriptor instead.
func (*GetKeygroupInfoResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{20}
}

func (x *GetKeygroupInfoResponse) GetMutable() bool {
	if x != nil {
		return x.Mutable
	}
	return false
}

func (x *GetKeygroupInfoResponse) GetReplica() []*KeygroupReplica {
	if x != nil {
		return x.Replica
	}
	return nil
}

type KeygroupReplica struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Expiry        int64                  `protobuf:"varint,2,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeygroupReplica) Reset() {
	*x = KeygroupReplica{}
	mi := &file_client_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeygroupReplica) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeygroupReplica) ProtoMessage() {}

func (x *KeygroupReplica) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeygroupReplica.ProtoReflect.Descriptor instead.
func (*KeygroupReplica) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{21}
}

func (x *KeygroupReplica) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *KeygroupReplica) GetExpiry() int64 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

func (x *KeygroupReplica) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type RemoveReplicaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keygroup      string                 `protobuf:"bytes,1,opt,name=keygroup,proto3" json:"keygroup,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveReplicaRequest) Reset() {
	*x = RemoveReplicaRequest{}
	mi := &file_client_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveReplicaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveReplicaRequest) ProtoMessage() {}

func (x *RemoveReplicaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveReplicaRequest.ProtoReflect.Descriptor instead.
func (*RemoveReplicaRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{22}
}

func (x *RemoveReplicaRequest) GetKeygroup() string {
	if x != nil {
		return x.Keygroup
	}
	return ""
}

func (x *RemoveReplicaRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetReplicaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReplicaRequest) Reset() {
	*x = GetReplicaRequest{}
	mi := &file_client_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReplicaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplicaRequest) ProtoMessage() {}

func (x *GetReplicaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplicaRequest.ProtoReflect.Descriptor instead.
func (*GetReplicaRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{23}
}

func (x *GetReplicaRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetReplicaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReplicaResponse) Reset() {
	*x = GetReplicaResponse{}
	mi := &file_client_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReplicaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplicaResponse) ProtoMessage() {}

func (x *GetReplicaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplicaResponse.ProtoReflect.Descriptor instead.
func (*GetReplicaResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{24}
}

func (x *GetReplicaResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetReplicaResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type Replica struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Replica) Reset() {
	*x = Replica{}
	mi := &file_client_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Replica) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Replica) ProtoMessage() {}

func (x *Replica) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Replica.ProtoReflect.Descriptor instead.
func (*Replica) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{25}
}

func (x *Replica) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Replica) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type GetAllReplicaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replicas      []*Replica             `protobuf:"bytes,1,rep,name=replicas,proto3" json:"replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllReplicaResponse) Reset() {
	*x = GetAllReplicaResponse{}
	mi := &file_client_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllReplicaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllReplicaResponse) ProtoMessage() {}

func (x *GetAllReplicaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllReplicaResponse.ProtoReflect.Descriptor instead.
func (*GetAllReplicaResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{26}
}

func (x *GetAllReplicaResponse) GetReplicas() []*Replica {
	if x != nil {
		return x.Replicas
	}
	return nil
}

type GetKeygroupTriggerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keygroup      string                 `protobuf:"bytes,1,opt,name=keygroup,proto3" json:"keygroup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeygroupTriggerRequest) Reset() {
	*x = GetKeygroupTriggerRequest{}
	mi := &file_client_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeygroupTriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeygroupTriggerRequest) ProtoMessage() {}

func (x *GetKeygroupTriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeygroupTriggerRequest.ProtoReflect.Descriptor instead.
func (*GetKeygroupTriggerRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{27}
}

func (x *GetKeygroupTriggerRequest) GetKeygroup() string {
	if x != nil {
		return x.Keygroup
	}
	return ""
}

type GetKeygroupTriggerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Triggers      []*Trigger             `protobuf:"bytes,1,rep,name=triggers,proto3" json:"triggers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeygroupTriggerResponse) Reset() {
	*x = GetKeygroupTriggerResponse{}
	mi := &file_client_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeygroupTriggerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeygroupTriggerResponse) ProtoMessage() {}

func (x *GetKeygroupTriggerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeygroupTriggerResponse.ProtoReflect.Descriptor instead.
func (*GetKeygroupTriggerResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{28}
}

func (x *GetKeygroupTriggerResponse) GetTriggers() []*Trigger {
	if x != nil {
		return x.Triggers
	}
	return nil
}

type Trigger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Host          string                 `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trigger) Reset() {
	*x = Trigger{}
	mi := &file_client_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trigger) ProtoMessage() {}

func (x *Trigger) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trigger.ProtoReflect.Descriptor instead.
func (*Trigger) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{29}
}

func (x *Trigger) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Trigger) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

type AddTriggerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keygroup      string                 `protobuf:"bytes,1,opt,name=keygroup,proto3" json:"keygroup,omitempty"`
	TriggerId     string                 `protobuf:"bytes,2,opt,name=triggerId,proto3" json:"triggerId,omitempty"`
	TriggerHost   string                 `protobuf:"bytes,3,opt,name=triggerHost,proto3" json:"triggerHost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTriggerRequest) Reset() {
	*x = AddTriggerRequest{}
	mi := &file_client_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTriggerRequest) ProtoMessage() {}

func (x *AddTriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTriggerRequest.ProtoReflect.Descriptor instead.
func (*AddTriggerRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{30}
}

func (x *AddTriggerRequest) GetKeygroup() string {
	if x != nil {
		return x.Keygroup
	}
	return ""
}

func (x *AddTriggerRequest) GetTriggerId() string {
	if x != nil {
		return x.TriggerId
	}
	return ""
}

func (x *AddTriggerRequest) GetTriggerHost() string {
	if x != nil {
		return x.TriggerHost
	}
	return ""
}

type RemoveTriggerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keygroup      string                 `protobuf:"bytes,1,opt,name=keygroup,proto3" json:"keygroup,omitempty"`
	TriggerId     string                 `protobuf:"bytes,2,opt,name=triggerId,proto3" json:"triggerId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTriggerRequest) Reset() {
	*x = RemoveTriggerRequest{}
	mi := &file_client_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTriggerRequest) ProtoMessage() {}

func (x *RemoveTriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTriggerRequest.ProtoReflect.Descriptor instead.
func (*RemoveTriggerRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{31}
}

func (x *RemoveTriggerRequest) GetKeygroup() string {
	if x != nil {
		return x.Keygroup
	}
	return ""
}

func (x *RemoveTriggerRequest) GetTriggerId() string {
	if x != nil {
		return x.TriggerId
	}
	return ""
}

type AddUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Keygroup      string                 `protobuf:"bytes,2,opt,name=keygroup,proto3" json:"keygroup,omitempty"`
	Role          UserRole               `protobuf:"varint,3,opt,name=role,proto3,enum=mcc.fred.client.UserRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserRequest) Reset() {
	*x = AddUserRequest{}
	mi := &file_client_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserRequest) ProtoMessage() {}

func (x *AddUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserRequest.ProtoReflect.Descriptor instead.
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{32}
}

func (x *AddUserRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *AddUserRequest) GetKeygroup() string {
	if x != nil {
		return x.Keygroup
	}
	return ""
}

func (x *AddUserRequest) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_ReadKeygroup
}

type RemoveUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Keygroup      string                 `protobuf:"bytes,2,opt,name=keygroup,proto3" json:"keygroup,omitempty"`
	Role          UserRole               `protobuf:"varint,3,opt,name=role,proto3,enum=mcc.fred.client.UserRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserRequest) Reset() {
	*x = RemoveUserRequest{}
	mi := &file_client_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserRequest) ProtoMessage() {}

func (x *RemoveUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{33}
}

func (x *RemoveUserRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *RemoveUserRequest) GetKeygroup() string {
	if x != nil {
		return x.Keygroup
	}
	return ""
}

func (x *RemoveUserRequest) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_ReadKeygroup
}

var File_client_proto protoreflect.FileDescriptor

const file_client_proto_rawDesc = "" +
	"\n" +
	"\fclient.proto\x12\x0fmcc.fred.client\"\a\n" +
	"\x05Empty\"\x86\x01\n" +
	"\aVersion\x12?\n" +
	"\aversion\x18\x01 \x03(\v2%.mcc.fred.client.Version.VersionEntryR\aversion\x1a:\n" +
	"\fVersionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"e\n" +
	"\x15CreateKeygroupRequest\x12\x1a\n" +
	"\bkeygroup\x18\x01 \x01(\tR\bkeygroup\x12\x18\n" +
	"\amutable\x18\x02 \x01(\bR\amutable\x12\x16\n" +
	"\x06expiry\x18\x03 \x01(\x03R\x06expiry\"3\n" +
	"\x15DeleteKeygroupRequest\x12\x1a\n" +
	"\bkeygroup\x18\x01 \x01(\tR\bkeygroup\"o\n" +
	"\vReadRequest\x12\x1a\n" +
	"\bkeygroup\x18\x01 \x01(\tR\bkeygroup\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x124\n" +
	"\bversions\x18\x03 \x03(\v2\x18.mcc.fred.client.VersionR\bversions\"\\\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03val\x18\x02 \x01(\tR\x03val\x122\n" +
	"\aversion\x18\x03 \x01(\v2\x18.mcc.fred.client.VersionR\aversion\"9\n" +
	"\fReadResponse\x12)\n" +
	"\x04data\x18\x01 \x03(\v2\x15.mcc.fred.client.ItemR\x04data\"O\n" +
	"\vScanRequest\x12\x1a\n" +
	"\bkeygroup\x18\x01 \x01(\tR\bkeygroup\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x04R\x05count\"9\n" +
	"\fScanResponse\x12)\n" +
	"\x04data\x18\x01 \x03(\v2\x15.mcc.fred.client.ItemR\x04data\"O\n" +
	"\vKeysRequest\x12\x1a\n" +
	"\bkeygroup\x18\x01 \x01(\tR\bkeygroup\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x04R\x05count\"I\n" +
	"\x03Key\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x122\n" +
	"\aversion\x18\x02 \x01(\v2\x18.mcc.fred.client.VersionR\aversion\"8\n" +
	"\fKeysResponse\x12(\n" +
	"\x04keys\x18\x01 \x03(\v2\x14.mcc.fred.client.KeyR\x04keys\"\x85\x01\n" +
	"\rUpdateRequest\x12\x1a\n" +
	"\bkeygroup\x18\x01 \x01(\tR\bkeygroup\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x124\n" +
	"\bversions\x18\x04 \x03(\v2\x18.mcc.fred.client.VersionR\bversions\"D\n" +
	"\x0eUpdateResponse\x122\n" +
	"\aversion\x18\x01 \x01(\v2\x18.mcc.fred.client.VersionR\aversion\"O\n" +
	"\rAppendRequest\x12\x1a\n" +
	"\bkeygroup\x18\x01 \x01(\tR\bkeygroup\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x04R\x02id\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\" \n" +
	"\x0eAppendResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"q\n" +
	"\rDeleteRequest\x12\x1a\n" +
	"\bkeygroup\x18\x01 \x01(\tR\bkeygroup\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x124\n" +
	"\bversions\x18\x03 \x03(\v2\x18.mcc.fred.client.VersionR\bversions\"D\n" +
	"\x0eDeleteResponse\x122\n" +
	"\aversion\x18\x01 \x01(\v2\x18.mcc.fred.client.VersionR\aversion\"_\n" +
	"\x11AddReplicaRequest\x12\x1a\n" +
	"\bkeygroup\x18\x01 \x01(\tR\bkeygroup\x12\x16\n" +
	"\x06nodeId\x18\x02 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06expiry\x18\x03 \x01(\x03R\x06expiry\"4\n" +
	"\x16GetKeygroupInfoRequest\x12\x1a\n" +
	"\bkeygroup\x18\x01 \x01(\tR\bkeygroup\"o\n" +
	"\x17GetKeygroupInfoResponse\x12\x18\n" +
	"\amutable\x18\x01 \x01(\bR\amutable\x12:\n" +
	"\areplica\x18\x02 \x03(\v2 .mcc.fred.client.KeygroupReplicaR\areplica\"U\n" +
	"\x0fKeygroupReplica\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06expiry\x18\x02 \x01(\x03R\x06expiry\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\"J\n" +
	"\x14RemoveReplicaRequest\x12\x1a\n" +
	"\bkeygroup\x18\x01 \x01(\tR\bkeygroup\x12\x16\n" +
	"\x06nodeId\x18\x02 \x01(\tR\x06nodeId\"+\n" +
	"\x11GetReplicaRequest\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\tR\x06nodeId\"@\n" +
	"\x12GetReplicaResponse\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\"5\n" +
	"\aReplica\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\"M\n" +
	"\x15GetAllReplicaResponse\x124\n" +
	"\breplicas\x18\x01 \x03(\v2\x18.mcc.fred.client.ReplicaR\breplicas\"7\n" +
	"\x19GetKeygroupTriggerRequest\x12\x1a\n" +
	"\bkeygroup\x18\x01 \x01(\tR\bkeygroup\"R\n" +
	"\x1aGetKeygroupTriggerResponse\x124\n" +
	"\btriggers\x18\x01 \x03(\v2\x18.mcc.fred.client.TriggerR\btriggers\"-\n" +
	"\aTrigger\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04host\x18\x02 \x01(\tR\x04host\"o\n" +
	"\x11AddTriggerRequest\x12\x1a\n" +
	"\bkeygroup\x18\x01 \x01(\tR\bkeygroup\x12\x1c\n" +
	"\ttriggerId\x18\x02 \x01(\tR\ttriggerId\x12 \n" +
	"\vtriggerHost\x18\x03 \x01(\tR\vtriggerHost\"P\n" +
	"\x14RemoveTriggerRequest\x12\x1a\n" +
	"\bkeygroup\x18\x01 \x01(\tR\bkeygroup\x12\x1c\n" +
	"\ttriggerId\x18\x02 \x01(\tR\ttriggerId\"o\n" +
	"\x0eAddUserRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x1a\n" +
	"\bkeygroup\x18\x02 \x01(\tR\bkeygroup\x12-\n" +
	"\x04role\x18\x03 \x01(\x0e2\x19.mcc.fred.client.UserRoleR\x04role\"r\n" +
	"\x11RemoveUserRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x1a\n" +
	"\bkeygroup\x18\x02 \x01(\tR\bkeygroup\x12-\n" +
	"\x04role\x18\x03 \x01(\x0e2\x19.mcc.fred.client.UserRoleR\x04role*s\n" +
	"\bUserRole\x12\x10\n" +
	"\fReadKeygroup\x10\x00\x12\x11\n" +
	"\rWriteKeygroup\x10\x01\x12\x14\n" +
	"\x10ConfigureReplica\x10\x02\x12\x14\n" +
	"\x10ConfigureTrigger\x10\x03\x12\x16\n" +
	"\x12ConfigureKeygroups\x10\x042\x9c\v\n" +
	"\x06Client\x12P\n" +
	"\x0eCreateKeygroup\x12&.mcc.fred.client.CreateKeygroupRequest\x1a\x16.mcc.fred.client.Empty\x12P\n" +
	"\x0eDeleteKeygroup\x12&.mcc.fred.client.DeleteKeygroupRequest\x1a\x16.mcc.fred.client.Empty\x12C\n" +
	"\x04Read\x12\x1c.mcc.fred.client.ReadRequest\x1a\x1d.mcc.fred.client.ReadResponse\x12C\n" +
	"\x04Scan\x12\x1c.mcc.fred.client.ScanRequest\x1a\x1d.mcc.fred.client.ScanResponse\x12C\n" +
	"\x04Keys\x12\x1c.mcc.fred.client.KeysRequest\x1a\x1d.mcc.fred.client.KeysResponse\x12I\n" +
	"\x06Update\x12\x1e.mcc.fred.client.UpdateRequest\x1a\x1f.mcc.fred.client.UpdateResponse\x12I\n" +
	"\x06Delete\x12\x1e.mcc.fred.client.DeleteRequest\x1a\x1f.mcc.fred.client.DeleteResponse\x12I\n" +
	"\x06Append\x12\x1e.mcc.fred.client.AppendRequest\x1a\x1f.mcc.fred.client.AppendResponse\x12H\n" +
	"\n" +
	"AddReplica\x12\".mcc.fred.client.AddReplicaRequest\x1a\x16.mcc.fred.client.Empty\x12d\n" +
	"\x0fGetKeygroupInfo\x12'.mcc.fred.client.GetKeygroupInfoRequest\x1a(.mcc.fred.client.GetKeygroupInfoResponse\x12N\n" +
	"\rRemoveReplica\x12%.mcc.fred.client.RemoveReplicaRequest\x1a\x16.mcc.fred.client.Empty\x12U\n" +
	"\n" +
	"GetReplica\x12\".mcc.fred.client.GetReplicaRequest\x1a#.mcc.fred.client.GetReplicaResponse\x12O\n" +
	"\rGetAllReplica\x12\x16.mcc.fred.client.Empty\x1a&.mcc.fred.client.GetAllReplicaResponse\x12n\n" +
	"\x13GetKeygroupTriggers\x12*.mcc.fred.client.GetKeygroupTriggerRequest\x1a+.mcc.fred.client.GetKeygroupTriggerResponse\x12H\n" +
	"\n" +
	"AddTrigger\x12\".mcc.fred.client.AddTriggerRequest\x1a\x16.mcc.fred.client.Empty\x12N\n" +
	"\rRemoveTrigger\x12%.mcc.fred.client.RemoveTriggerRequest\x1a\x16.mcc.fred.client.Empty\x12B\n" +
	"\aAddUser\x12\x1f.mcc.fred.client.AddUserRequest\x1a\x16.mcc.fred.client.Empty\x12H\n" +
	"\n" +
	"RemoveUser\x12\".mcc.fred.client.RemoveUserRequest\x1a\x16.mcc.fred.client.EmptyB\x0eZ\f.;fredclientb\x06proto3"

var (
	file_client_proto_rawDescOnce sync.Once
	file_client_proto_rawDescData []byte
)

func file_client_proto_rawDescGZIP() []byte {
	file_client_proto_rawDescOnce.Do(func() {
		file_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_proto_rawDesc), len(file_client_proto_rawDesc)))
	})
	return file_client_proto_rawDescData
}

var file_client_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_client_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_client_proto_goTypes = []any{
	(UserRole)(0),                      // 0: mcc.fred.client.UserRole
	(*Empty)(nil),                      // 1: mcc.fred.client.Empty
	(*Version)(nil),                    // 2: mcc.fred.client.Version
	(*CreateKeygroupRequest)(nil),      // 3: mcc.fred.client.CreateKeygroupRequest
	(*DeleteKeygroupRequest)(nil),      // 4: mcc.fred.client.DeleteKeygroupRequest
	(*ReadRequest)(nil),                // 5: mcc.fred.client.ReadRequest
	(*Item)(nil),                       // 6: mcc.fred.client.Item
	(*ReadResponse)(nil),               // 7: mcc.fred.client.ReadResponse
	(*ScanRequest)(nil),                // 8: mcc.fred.client.ScanRequest
	(*ScanResponse)(nil),               // 9: mcc.fred.client.ScanResponse
	(*KeysRequest)(nil),                // 10: mcc.fred.client.KeysRequest
	(*Key)(nil),                        // 11: mcc.fred.client.Key
	(*KeysResponse)(nil),               // 12: mcc.fred.client.KeysResponse
	(*UpdateRequest)(nil),              // 13: mcc.fred.client.UpdateRequest
	(*UpdateResponse)(nil),             // 14: mcc.fred.client.UpdateResponse
	(*AppendRequest)(nil),              // 15: mcc.fred.client.AppendRequest
	(*AppendResponse)(nil),             // 16: mcc.fred.client.AppendResponse
	(*DeleteRequest)(nil),              // 17: mcc.fred.client.DeleteRequest
	(*DeleteResponse)(nil),             // 18: mcc.fred.client.DeleteResponse
	(*AddReplicaRequest)(nil),          // 19: mcc.fred.client.AddReplicaRequest
	(*GetKeygroupInfoRequest)(nil),     // 20: mcc.fred.client.GetKeygroupInfoRequest
	(*GetKeygroupInfoResponse)(nil),    // 21: mcc.fred.client.GetKeygroupInfoResponse
	(*KeygroupReplica)(nil),            // 22: mcc.fred.client.KeygroupReplica
	(*RemoveReplicaRequest)(nil),       // 23: mcc.fred.client.RemoveReplicaRequest
	(*GetReplicaRequest)(nil),          // 24: mcc.fred.client.GetReplicaRequest
	(*GetReplicaResponse)(nil),         // 25: mcc.fred.client.GetReplicaResponse
	(*Replica)(nil),                    // 26: mcc.fred.client.Replica
	(*GetAllReplicaResponse)(nil),      // 27: mcc.fred.client.GetAllReplicaResponse
	(*GetKeygroupTriggerRequest)(nil),  // 28: mcc.fred.client.GetKeygroupTriggerRequest
	(*GetKeygroupTriggerResponse)(nil), // 29: mcc.fred.client.GetKeygroupTriggerResponse
	(*Trigger)(nil),                    // 30: mcc.fred.client.Trigger
	(*AddTriggerRequest)(nil),          // 31: mcc.fred.client.AddTriggerRequest
	(*RemoveTriggerRequest)(nil),       // 32: mcc.fred.client.RemoveTriggerRequest
	(*AddUserRequest)(nil),             // 33: mcc.fred.client.AddUserRequest
	(*RemoveUserRequest)(nil),          // 34: mcc.fred.client.RemoveUserRequest
	nil,                                // 35: mcc.fred.client.Version.VersionEntry
}
var file_client_proto_depIdxs = []int32{
	35, // 0: mcc.fred.client.Version.version:type_name -> mcc.fred.client.Version.VersionEntry
	2,  // 1: mcc.fred.client.ReadRequest.versions:type_name -> mcc.fred.client.Version
	2,  // 2: mcc.fred.client.Item.version:type_name -> mcc.fred.client.Version
	6,  // 3: mcc.fred.client.ReadResponse.data:type_name -> mcc.fred.client.Item
	6,  // 4: mcc.fred.client.ScanResponse.data:type_name -> mcc.fred.client.Item
	2,  // 5: mcc.fred.client.Key.version:type_name -> mcc.fred.client.Version
	11, // 6: mcc.fred.client.KeysResponse.keys:type_name -> mcc.fred.client.Key
	2,  // 7: mcc.fred.client.UpdateRequest.versions:type_name -> mcc.fred.client.Version
	2,  // 8: mcc.fred.client.UpdateResponse.version:type_name -> mcc.fred.client.Version
	2,  // 9: mcc.fred.client.DeleteRequest.versions:type_name -> mcc.fred.client.Version
	2,  // 10: mcc.fred.client.DeleteResponse.version:type_name -> mcc.fred.client.Version
	22, // 11: mcc.fred.client.GetKeygroupInfoResponse.replica:type_name -> mcc.fred.client.KeygroupReplica
	26, // 12: mcc.fred.client.GetAllReplicaResponse.replicas:type_name -> mcc.fred.client.Replica
	30, // 13: mcc.fred.client.GetKeygroupTriggerResponse.triggers:type_name -> mcc.fred.client.Trigger
	0,  // 14: mcc.fred.client.AddUserRequest.role:type_name -> mcc.fred.client.UserRole
	0,  // 15: mcc.fred.client.RemoveUserRequest.role:type_name -> mcc.fred.client.UserRole
	3,  // 16: mcc.fred.client.Client.CreateKeygroup:input_type -> mcc.fred.client.CreateKeygroupRequest
	4,  // 17: mcc.fred.client.Client.DeleteKeygroup:input_type -> mcc.fred.client.DeleteKeygroupRequest
	5,  // 18: mcc.fred.client.Client.Read:input_type -> mcc.fred.client.ReadRequest
	8,  // 19: mcc.fred.client.Client.Scan:input_type -> mcc.fred.client.ScanRequest
	10, // 20: mcc.fred.client.Client.Keys:input_type -> mcc.fred.client.KeysRequest
	13, // 21: mcc.fred.client.Client.Update:input_type -> mcc.fred.client.UpdateRequest
	17, // 22: mcc.fred.client.Client.Delete:input_type -> mcc.fred.client.DeleteRequest
	15, // 23: mcc.fred.client.Client.Append:input_type -> mcc.fred.client.AppendRequest
	19, // 24: mcc.fred.client.Client.AddReplica:input_type -> mcc.fred.client.AddReplicaRequest
	20, // 25: mcc.fred.client.Client.GetKeygroupInfo:input_type -> mcc.fred.client.GetKeygroupInfoRequest
	23, // 26: mcc.fred.client.Client.RemoveReplica:input_type -> mcc.fred.client.RemoveReplicaRequest
	24, // 27: mcc.fred.client.Client.GetReplica:input_type -> mcc.fred.client.GetReplicaRequest
	1,  // 28: mcc.fred.client.Client.GetAllReplica:input_type -> mcc.fred.client.Empty
	28, // 29: mcc.fred.client.Client.GetKeygroupTriggers:input_type -> mcc.fred.client.GetKeygroupTriggerRequest
	31, // 30: mcc.fred.client.Client.AddTrigger:input_type -> mcc.fred.client.AddTriggerRequest
	32, // 31: mcc.fred.client.Client.RemoveTrigger:input_type -> mcc.fred.client.RemoveTriggerRequest
	33, // 32: mcc.fred.client.Client.AddUser:input_type -> mcc.fred.client.AddUserRequest
	34, // 33: mcc.fred.client.Client.RemoveUser:input_type -> mcc.fred.client.RemoveUserRequest
	1,  // 34: mcc.fred.client.Client.CreateKeygroup:output_type -> mcc.fred.client.Empty
	1,  // 35: mcc.fred.client.Client.DeleteKeygroup:output_type -> mcc.fred.client.Empty
	7,  // 36: mcc.fred.client.Client.Read:output_type -> mcc.fred.client.ReadResponse
	9,  // 37: mcc.fred.client.Client.Scan:output_type -> mcc.fred.client.ScanResponse
	12, // 38: mcc.fred.client.Client.Keys:output_type -> mcc.fred.client.KeysResponse
	14, // 39: mcc.fred.client.Client.Update:output_type -> mcc.fred.client.UpdateResponse
	18, // 40: mcc.fred.client.Client.Delete:output_type -> mcc.fred.client.DeleteResponse
	16, // 41: mcc.fred.client.Client.Append:output_type -> mcc.fred.client.AppendResponse
	1,  // 42: mcc.fred.client.Client.AddReplica:output_type -> mcc.fred.client.Empty
	21, // 43: mcc.fred.client.Client.GetKeygroupInfo:output_type -> mcc.fred.client.GetKeygroupInfoResponse
	1,  // 44: mcc.fred.client.Client.RemoveReplica:output_type -> mcc.fred.client.Empty
	25, // 45: mcc.fred.client.Client.GetReplica:output_type -> mcc.fred.client.GetReplicaResponse
	27, // 46: mcc.fred.client.Client.GetAllReplica:output_type -> mcc.fred.client.GetAllReplicaResponse
	29, // 47: mcc.fred.client.Client.GetKeygroupTriggers:output_type -> mcc.fred.client.GetKeygroupTriggerResponse
	1,  // 48: mcc.fred.client.Client.AddTrigger:output_type -> mcc.fred.client.Empty
	1,  // 49: mcc.fred.client.Client.RemoveTrigger:output_type -> mcc.fred.client.Empty
	1,  // 50: mcc.fred.client.Client.AddUser:output_type -> mcc.fred.client.Empty
	1,  // 51: mcc.fred.client.Client.RemoveUser:output_type -> mcc.fred.client.Empty
	34, // [34:52] is the sub-list for method output_type
	16, // [16:34] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_client_proto_init() }
func file_client_proto_init() {
	if File_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_proto_rawDesc), len(file_client_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_proto_goTypes,
		DependencyIndexes: file_client_proto_depIdxs,
		EnumInfos:         file_client_proto_enumTypes,
		MessageInfos:      file_client_proto_msgTypes,
	}.Build()
	File_client_proto = out.File
	file_client_proto_goTypes = nil
	file_client_proto_depIdxs = nil
}
